### ISSUE TITLE
Nicer UI

### ISSUE THREAD

**Issue by ltzehan** [AY2223S2-CS2113-F10-1/tp#157]
`card list` should truncate long question and answers after a certain length:
![image](https://user-images.githubusercontent.com/40513040/229331554-50a5f3e1-4270-4e68-bb4c-8be79032a38e.png)

Also, tags and decks should use their names instead of UUID for clarity
![image](https://user-images.githubusercontent.com/40513040/229331607-200113ba-870e-4c3c-8b70-ec7b6d9c9af4.png)

**Comment by mitchmalvin1** [comment]
Showing the tag name and deck name in card is not trivial. This is because we cannot simply edit the `toString` of Card as it will not have access to `tagList` or `deckList`. An option is to not do this in the `toString` of card but that will mean every time we need to display a Card (`card view` , `card tag` `card list` ), we need to manually call the functions to display the `tags` and `decks` instead of simply printing Card.

**Comment by ltzehan** [comment]
> Showing the tag name and deck name in card is not trivial. This is because we cannot simply edit the `toString` of Card as it will not have access to `tagList` or `deckList`. An option is to not do this in the `toString` of card but that will mean every time we need to display a Card (`card view` , `card tag` `card list` ), we need to manually call the functions to display the `tags` and `decks` instead of simply printing Card. Will that be preferable? If yes then I'll go and implement it.

That's a good point, but I think it's worthwhile to implement. We could either do:
- Store deck/tag name alongside deck/tag UUID in`Card`
- Let `UserInterface` handle mapping deck/tag UUIDs to deck/tag names

I think the latter is preferable and one way I can think of implementing it is to add a hashmap from deck/tag UUID -> deck/tag name in `TagList`/`DeckList`. Should be fairly straightforward since we have add and delete methods, and we can make our search functions O(1)

**Comment by mitchmalvin1** [comment]
I just manually searched for the relevant tags in decks in `card view`, since `card list` does not need to show the tags and decks. Anyway, the UI has been enhanced
. 
<img width="1155" alt="Screenshot 2023-04-02 at 10 35 09 PM" src="https://user-images.githubusercontent.com/89574448/229359752-ae00122b-d52e-45c5-a716-e6451a2cbf7c.png">

**Comment by ltzehan** [comment]
@mitchmalvin1 Can this be closed?
